# Generated by Django 4.2.13 on 2024-09-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_price_product_is_active_productline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLine',
        ),
    ]
